baseurl      = "https://maverickzj.github.io"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disableRSS     = false
disableSitemap = false


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "躲进小楼成一统。"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

enableGlobalLanguageMenu = false


  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

enableThemeToggle = true


[params.footer]
    trademark = 0
    rss = 0
    copyright = 0
    author = 0

topText = ["aaaeeeiii"]
    bottomText = [
      "2023-"
    ]

 [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "小言詹詹"
    subtitle = "kzysblog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "小言詹詹"
      logoHomeLink = ""
    # or
    #
    path = "/icon.svg"
    alt = ""

  # And you can even create generic menu
  [[menu.main]]
      identifier = "home"
      name       = "首页"
      url        = "/"

  [[menu.main]]
    identifier = "posts"
    name       = "随便写写"
    url        = "/posts"

  [[menu.main]]
    identifier = "notes"
    name       = "笔记"
    url        = "/notes"

  [[menu.main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives"

[[menu.main]]
    identifier = "RSS"
    name       = "RSS"
    url        = "https://maverickzj.github.io/index.xml"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html','rss']
  term = ['html','rss']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true





